name: Add a composer

on:
  workflow_dispatch:
    inputs:
      composer:
        description: "The composer to add"
        required: true
      branch_name:
        description: "The name of the branch to create"
        required: true

jobs:
  run_add_composers_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" # Adjust this to your required Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r data_collection/requirements.txt

      - name: Run script.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python data_collection/add_composer.py --composer "${{ github.event.inputs.composer }}" --target=public/data

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: "main"
          branch: add-composer-${{ github.event.inputs.branch_name }}
          commit-message: Add composer ${{ github.event.inputs.composer }}
          title: Add composer ${{ github.event.inputs.composer }}
          body: "This PR was created automatically by GitHub Actions."
          reviewers: "zulko"
          delete-branch: true
